language: Java
jdk:
- oraclejdk8
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
before_deploy:
- ./gradlew releaseZip
deploy:
  provider: releases
  api_key:
    secure: MJcmcAaxN9olicmbnJWI+LLzSaUrLk/UujSu68mmt8sHgi72K3pM30ZpcowHHIWlIamBOmp8WZSf/KYfVjpTbhsfvIojLZJkvEi5HEeKR/cG7jyacNcAs8mmjK+lH6ZofV34IRZmqXP0A5OKtpbYEIpf9p91OHR8duibKHRM1gltGqdqWHWd0RaInXdFfF5NGF8NZMZ3EgEQVBGT6bmId7s+MH5J4qUp9hDmCzvC4I+tVgKtP+hiBj4W7mFptJxf9oU0B9MPGnKXE9CTj9Vmz2SD/R52aRL+587amfJ9y7c6kfdPrXAp4X8EJBG1ABongxAuz1aqCroY7QXJdVzLF4vLQsEGnqlTUdS2OdmhJasGmGz3QunRmjMTqj+3gEiyGkgng1xXo6gPRaRmcUd+5X+uRQwM7zEU6GBA+sjhpe6KAS8Xme+P4MnLAfGITh/DLhuYiMGN3JJDEwYZg4kH81S/9+1k46oNvXryKvtuznIk1M/nJEI8gs/EzC2khhVi+cINW1549dj10D+P+LPC8Q/MKD6Ga4Yudv4td5lxGtxe13GshOobD5Mde0URem2dajyXrfwMqvRbgy4SvLIQ+vwUexZknfkdZPWVpo6VzcRc7nQTs5KLO/abCMf4lFvkcJcMzxAqV3ECkJffscqnrGj6ou/LBVWpihZeeDkfzkM=
  file_glob: true
  file: "./build/libs/JAlgoArena-API-*.zip"
  skip_cleanup: true
  on:
    repo: skorzeniak/JAlgoArena-API
    tags: true
