server:
  port: 5001

zuul:
  ignoredServices: '*'
  routes:
    jalgoarena-judge: /judge/api/**
    jalgoarena-problems: /problems/api/**
    jalgoarena-auth: /auth/**
    jalgoarena-submissions: /submissions/api/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://sk-jalgoarena-eureka.herokuapp.com/eureka
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 30000
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
---
spring:
  profiles: heroku
eureka:
  instance:
    hostname: ${APP_NAME:sk-jalgoarena-api}.herokuapp.com
    nonSecurePort: 80

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
